In [11]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

url='https://raw.githubusercontent.com/jinnatul/ml-Pro/master/data/data-diabetes.csv?token=AHUDKE64XJ6B3G4J7GFMFEC7AAD74'
df = pd.read_csv(url)

df.head()

glucose  bloodpressure  diabetes
0       40             85         0
1       40             92         0
2       45             63         1
3       45             80         0
4       40             73         1

In [12]:
features=['glucose','bloodpressure']
x=df[features]
y=df.diabetes

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=5)

In [14]:
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
predictions = model.predict(x_test)
print (predictions)

[0 1 1 0 0 1 1 0 1 0 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 0 1 1 0 0 1 0 0 1 1 1
 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 1 0 0 1 1 0
 0 1 1 1 1 0 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0 0 0 0 0 0
 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0 1 1 0 1 0 0
 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 1 1 1 0 0 1 1 0 0 1
 0 0 1 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 0 0 1 0 1 0
 1 0 1 0 1 0 1 1 1 0 0 1 1 1 1 0 0 1 1 0 0 0 1 0 0 0 1]


In [16]:
# Model performance Report

 
print('Classification Report:\n',classification_report(y_test, predictions))
print('Confusion Matrix:\n',confusion_matrix(y_test, predictions))
print('Accuracy Score:',accuracy_score(y_test, predictions))
print("Precision:",metrics.precision_score(y_test, predictions))
print("Recall:",metrics.recall_score(y_test,predictions ))

Classification Report:
               precision    recall  f1-score   support

           0       0.97      0.92      0.94       123
           1       0.92      0.97      0.95       126

    accuracy                           0.94       249
   macro avg       0.95      0.94      0.94       249
weighted avg       0.94      0.94      0.94       249

Confusion Matrix:
 [[113  10]
 [  4 122]]
Accuracy Score: 0.9437751004016064
Precision: 0.9242424242424242
Recall: 0.9682539682539683


In [18]:
new_observation = [[40,65]]
model.predict(new_observation)

array([1])

In [23]:
new_observation = [[35,85]]
model.predict(new_observation)

array([0])

In [24]:
new_observation = [[42,55]]
model.predict(new_observation)

array([1])